# Generated by Django 3.2 on 2022-05-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='categories',
            new_name='category',
        ),
    ]
